# To use the "FiraCode NF" font, downlaod by searching on google "fira code nerd font" and select 
# "regular" style font

# https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/FiraCode/Regular/complete

# Colors (Gruvbox Material Dark Medium)
[colors.primary]
background= '0x282828'
#foreground= '0xdfbf8e'

[colors.normal]
black=   '0x665c54'
red=     '0xea6962'
green=   '0xa9b665'
yellow=  '0xe78a4e'
blue=    '0x7daea3'
magenta= '0xd3869b'
cyan=    '0x89b482'
white=   '0xdfbf8e'

[colors.bright]
black=   '0x928375'
red=     '0xea6962'
green=   '0xa9b665'
yellow=  '0xe3a84e'
blue=    '0x7daea3'
magenta= '0xd3869b'
cyan=    '0x89b482'
white=   '0xdfbf8e'

[font]
normal= { family= "FiraCode Nerd Font", style = "Regular" }
size = 10.25
# Offset "x" marks letter spacing and "y" marks line spacing
offset = { x = 0, y = 2 }
builtin_box_drawing = true

[cursor.style]
shape = "Beam"
blinking = "Always"

[window]
padding = { x = 8, y = 8 }
title = "Alacritty"
startup_mode = "Windowed"
dynamic_title = true
